#MakeFile to build and deploy the Sample US CENSUS Name Data using ajax
# For CSC3004 Software Development

# Put your user name below:
USER= liu4

all: PutCGI PutHTML

PutCGI:
	chmod 757 search.py
	cp search.py /usr/lib/cgi-bin/$(USER)search.py

	echo "Current contents of your cgi-bin directory: "
	ls -l /usr/lib/cgi-bin/


#need to change the directory
PutHTML:
	cp phoneApp.html /var/www/html/class/softdev/liu4/PhoneAppPython/
	cp phoneApp.css /var/www/html/class/softdev/liu4/PhoneAppPython/
	cp phoneApp.js /var/www/html/class/softdev/liu4/PhoneAppPython/

	echo "Current contents of your HTML directory: "
	ls -l /var/www/html/class/softdev/liu4/PhoneAppPython/
